#!/bin/bash
#
# Setup and installation of Oh My Zsh on OS X, using my conventions

set -e

GITHUB_USER=apjanke

function main() {

# Prerequisites:
#  git (may be provided by Xcode CLT)

# Install Oh My Zsh
# (using manual installation, because their install breaks $PATH)

omz_repos_dir=~/local/opp/oh-my-zsh
mkdir -p "$omz_repos_dir"
if [[ ! -e "$omz_repos_dir/oh-my-zsh" ]]; then
  echo "Cloning oh-my-zsh"
  git clone https://github.com/$GITHUB_USER/oh-my-zsh.git "$omz_repos_dir/oh-my-zsh"
  pushd "$omz_repos_dir/oh-my-zsh"
  git remote add upstream https://github.com/robbyrussell/oh-my-zsh
  git fetch --all
  popd
fi
if [[ ! -e "$omz_repos_dir/oh-my-zsh-custom" ]]; then
  local not_found=$(curl -s https://api.github.com/repos/$GITHUB_USER/oh-my-zsh-custom | grep "Not Found")
  if [[ -z "$not_found" ]]; then
    echo "Cloning oh-my-zsh-custom"
    git clone https://github.com/$GITHUB_USER/oh-my-zsh-custom "$omz_repos_dir/oh-my-zsh-custom"
  else
    echo "User $GITHUB_USER has no oh-my-zsh-custom repo; skipping"
  fi
fi
if [[ ! -e ~/.oh-my-zsh ]]; then
  echo "Linking .oh-my-zsh"
  ln -s "$omz_repos_dir/oh-my-zsh" ~/.oh-my-zsh
  echo "Linked ~/.oh-my-zsh. You will need to edit ~/.zshrc to source it."
fi
if [[ ! -e ~/.oh-my-zsh-custom ]]; then
  if [[ -e "$omz_repos_dir/oh-my-zsh-custom" ]]; then
    echo "Linking .oh-my-zsh-custom"
    ln -s "$omz_repos_dir/oh-my-zsh-custom" ~/.oh-my-zsh-custom
  else
    echo "No oh-my-zsh-custom repo is defined; skipping"
  fi
fi

if [[ $(uname) = Darwin ]]; then
  curr_shell=$(dscl /Search -read "/Users/$USER" UserShell | awk '{print $2}')
else
  curr_shell="$SHELL"
fi
if [[ $curr_shell != /bin/zsh ]]; then
  chsh -s /bin/zsh
fi

}

main; exit 0
