#!/bin/bash
# set-osx-hostname
#
# sudo set-osx-hostname <name>
#
# Sets the hostname in all the various ways you need to on OS X.
# This is intended to be the equivalent of manually setting it in the
# System Preferences > Sharing control panel.
#
# I'm not sure if it actually works

PROGRAM_NAME="$(basename $0)"

function usage() {
  cat <<EOF
$PROGRAM_NAME - set the hostname on this machine

Usage:
  $PROGRAM_NAME [-x] <hostname>
  $PROGRAM_NAME -h

Options:
    -x    trace program execution
    -h    display help
EOF
}

while getopts xh opt; do
  case $opt in
    x)
      OPT_TRACE=1
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      echo >&2 "See '$PROGRAM_NAME -h' for usage"
      exit 1
      ;;
  esac
done

if [[ -z "$1" ]]; then
  usage
  exit 1
fi

function set-osx-hostname() {
  name="$1"
  sudo scutil --set ComputerName "$name"
  sudo scutil --set HostName "$name"
  sudo scutil --set LocalHostName "$name"
  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$name"
}

function main() {
  set-osx-hostname "$1"
}

if [[ $OPT_TRACE == 1 ]]; then
  set -x
fi

main
